### PR TITLE
fix: configurations not loading from package.json

### LINKED ISSUE #486: When using entries in package.json options is not recognized properly
**Describe the bug**
Tried using the module, and found that when we provide value mappings in package.json, they are not recognized properly. Even after providing buildDir value with a custom path, the package still gets created inside target folder

**Expected behavior**
buildDir value should be honored for creation of package

**Screenshots and Logs**
Last line from log : AEM package has been created and can be found in the current user's Maven package repository or in ./target

**Environment (please complete the following information):**
 - OS: Windows and Mac
 - Version: [3.1.3]
 - NodeJS Version: [18.6.1]
 - NPM Version: [9.5.1]

**Additional context**
Found the root cause. When consolidating the config, instead of calling the method `getConfigsFromPackage` the method identifier is passed.

### PR DESCRIPTION
**Pull request by friendlymahi**
- Fixes : Package gets created in target folder instead of custom path provided

Fixes #486

## Proposed Changes

- Call the method `getConfigsFromPackage` instead of passing the identifier

### Before

Last line from log : AEM package has been created and can be found in the current user's Maven package repository or in ./target

### After

Last line from log : AEM package has been created and can be found in the current user's Maven package repository or in ./build-aem/package

## Background context

...fill in details explaining why this is important or this approach should be used to solve the issue...

### Where should the reviewer start / What requires special attention?

...specific files or actions...

### How should this be manually tested?

1. Create a new AEM project using react as frontend module type
2. Include `aem-packager` in package.json dev dependencies and then use entries below for `aem-packager` section for ui.frontend module
3. Update build script as `react-scripts build && clientlib && aem-packager`
4. Execute the command `npm i` followed by `npm build`
5. You shall see that package is created in target folder before this PR and will be the custom path mentioned in sample config section share in step2

### Questions:
- Does this add new dependencies (node, maven, ant, etc) that must be installed?
  -No
- Does this change the commands required to run this project?
  -No
- Are any environmental dependencies or operational support steps (sql commands, config changes, etc) required?
  -No
- Are there any relevant issues besides this one?
  - No

### CODE REVIEW

**Comment by friendlymahi** [comment]
@amclin - Requesting you to review this issue and PR, and if everything looks good, please merge the PR. Thanks !

**Comment by friendlymahi** [comment]
@amclin - hope you are doing well. can you please review this PR as I would like to use this package for our teams where aem or Java development is not required. If not feasible please let me know so I can copy over the code to our internal module and remove it once you merge the PR. Thanks

**Comment by amclin** [comment]
Thanks for the fix @friendlymahi !

**Comment by friendlymahi** [comment]
Thanks a lot for accepting the fix. Can you please review the other pr for new maven plug in version as the old one is or working as expected and not supported by Adobe any more.

**Pull request merged**
